# Generated by Django 5.1.4 on 2025-01-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='sentiment_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
